#author
# title
# body
# subreddit
# link to post

ALL_JOKES = [{'Author': 'Budget-Pay3743',
 'Body': "But I'll return.",
 'Link': 'https://www.reddit.com/r/dadjokes/comments/12zqy8r/i_got_booed_off_the_stage_at_the_comedy_club_for/',
 'Subreddit': 'dadjokes',
 'Title': 'I got booed off the stage at the comedy club for doing bad Arnold '
          'Schwarzenegger impressions'},
{'Author': 'crazyfortaco',
 'Body': 'My husband and I have been fighting so much lately. I am going to '
         'come live with you again."\n'
         '\n'
         'Her mother replies, "No dear, he should pay for his mistakes. I am '
         'coming to live with you."',
 'Link': 'https://www.reddit.com/r/dadjokes/comments/12zqfgs/a_woman_calls_her_mother/',
 'Subreddit': 'dadjokes',
 'Title': 'A woman calls her mother.'},
{'Author': 'Lunchindabox66',
 'Body': "The owner says it’s only been driven from time to time.",
 'Link': 'https://www.reddit.com/r/dadjokes/comments/12zq91b/ive_found_a_delorean_on_craigslist_its_got_low/',
 'Subreddit': 'dadjokes',
 'Title': "I’ve found a Delorean on Craigslist. It’s got low miles…"},
{'Author': 'skib900',
 'Body': 'Experi-mints',
 'Link': 'https://www.reddit.com/r/dadjokes/comments/12zq6qu/how_do_scientists_keep_their_breath_fresh/',
 'Subreddit': 'dadjokes',
 'Title': 'How do scientists keep their breath fresh?'},
{'Author': 'Naive_Piglet_III',
 'Body': "Wendy’s.",
 'Link': 'https://www.reddit.com/r/dadjokes/comments/12zpwp4/what_is_peter_pans_favourite_place_to_eat_out/',
 'Subreddit': 'dadjokes',
 'Title': "What is Peter Pan’s favourite place to eat out?"},
{'Author': 'thegreatjamoco',
 'Body': 'The ICU',
 'Link': 'https://www.reddit.com/r/dadjokes/comments/12zpw9b/where_does_one_go_to_cure_their_invisibility/',
 'Subreddit': 'dadjokes',
 'Title': 'Where does one go to cure their invisibility sickness?'},
{'Author': 'houndoom92',
 'Body': ' 6 out of 10 people',
 'Link': 'https://www.reddit.com/r/dadjokes/comments/12zpu2l/the_institute_of_unfinished_research_has/',
 'Subreddit': 'dadjokes',
 'Title': 'The Institute of Unfinished research has concluded that'},
{'Author': 'Unreversed_impulse09',
 'Body': 'Mopey Dick',
 'Link': 'https://www.reddit.com/r/dadjokes/comments/12zovhi/what_do_you_call_an_author_with_erectile/',
 'Subreddit': 'dadjokes',
 'Title': 'What do you call an author with erectile dysfunction?'},
{'Author': 'Mr_Geep',
 'Body': 'Hip Pop',
 'Link': 'https://www.reddit.com/r/dadjokes/comments/12znft4/what_is_a_chiroprators_favorite_music_genre/',
 'Subreddit': 'dadjokes',
 'Title': 'What is a Chiroprators favorite music genre?'},
{'Author': 'Nate_C_of_2003',
 'Body': 'It was just a douche',
 'Link': 'https://www.reddit.com/r/dadjokes/comments/12zne4t/this_feminine_hygiene_product_was_a_real_jerk_to/',
 'Subreddit': 'dadjokes',
 'Title': 'This feminine hygiene product was a real jerk to me today'},
{'Author': 'Different-Tie-1085',
 'Body': "They're not that significant!",
 'Link': 'https://www.reddit.com/r/dadjokes/comments/12zn32w/unless_you_can_rip_a_fart_in_front_of_your/',
 'Subreddit': 'dadjokes',
 'Title': 'Unless you can rip a fart in front of your significant other...'},
{'Author': 'superguavapulp',
 'Body': 'I am feeling a little light-headed now',
 'Link': 'https://www.reddit.com/r/dadjokes/comments/12zmupc/i_had_one_heck_of_a_haircut_today_while_drinking/',
 'Subreddit': 'dadjokes',
 'Title': 'I had one heck of a haircut today while drinking'},
{'Author': 'goldsilver650600',
 'Body': 'So I putter in her place.',
 'Link': 'https://www.reddit.com/r/dadjokes/comments/12zmcb0/my_gf_is_sick_of_my_golf_references/',
 'Subreddit': 'dadjokes',
 'Title': 'My GF is sick of my golf references.'},
{'Author': '____JayP',
 'Body': 'Because they have tiny ant-bodies!',
 'Link': 'https://www.reddit.com/r/dadjokes/comments/12zma0m/why_dont_ants_get_sick/',
 'Subreddit': 'dadjokes',
 'Title': "Why don't ants get sick?"}]